name: MavenBuild
run-name: Test - Trigger Jenkins Job

on:
  push:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Job Info
      run: echo "Job is executing as part of workflow - Alexander Neverov"

    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.8
        
    - name: Test with Maven
      run: mvn -B test --file pom.xml

    - name: Remote trigger Jenkins job
      run: sudo curl -I -u 116c33431659a404940a96a59305eb41a6 https://657c-170-103-40-174.ngrok-free.app/job/IA/build?token=tokennew 
      
